main: me.tajam.jext.Jext
name: JukeboxExtended
version: 0.1
api-version: 1.15
depend: [ProtocolLib]
commands:
  disc:
    description: Get the specified custom music disc.
    usage: /disc [name]
  playmusic:
    description: Play specified custom music at executor location.
    usage: /playmusic [name] <volume> <pitch>
  stopmusic:
    description: Stop specified custom music or all music
    usage: /stopmusic <name>